# fileops.sol — everyday filesystem automation, transactionally.
#
# Compared to bash: bash mutates as each line runs, so a mid-script failure
# leaves a half-done mess. Here EVERY file write, removal, and mkdir is
# buffered and applied atomically at the end — nothing touches disk until
# the whole script validates. Read-only tool calls (sh) run immediately;
# mutating tool calls (shq) queue for commit. If a concurrent process
# changes a file we read, we abort and re-run — deferred effects never fire.
#
# mkdirp = create a dir and all its parents if needed, atomically. If the dir already exists, do nothing.
# writePath = write a file atomically, creating parent dirs if needed. If the file already exists, overwrite it.
# readPath = read a file into a string. If the file doesn't exist, abort.
# (absence expected? spell it: readPathOr for a default, Try.readPath for
#  the Ok/Err chain — see tryops.sol for the pattern.)
#
# BUILTINS FIRST: the prelude's Str.* / List.* / booleans cover the
# everyday shapes, so a script is pipelines over them, not a helper zoo.

base = use "../lib/base".

# ---- a mini "project scaffolder": create a dir tree + files atomically ----
scaffold root =
  u0 = mkdirp "{root}/src";
  u1 = mkdirp "{root}/test";
  u2 = writePath "{root}/README.md" "# {base.baseName root}\n\ngenerated by sol\n";
  u3 = writePath "{root}/src/main.sol" "> print \"hello from {base.baseName root}\".\n";
  u4 = writePath "{root}/test/basic.sol" "> print \"test stub\".\n";
  print "scaffolded {root} (4 files, 2 dirs) — atomic".

# ---- count lines across a directory of files (like wc -l *) ----
lineCountAll dir =
  total = ls dir
    |> List.filter (fn n -> not (isDir "{dir}/{n}"))
    |> List.map (fn n -> List.len (Str.lines (readPath "{dir}/{n}")))
    |> List.sum;
  print "total lines under {dir}: {total}".

# ---- prune: remove all files matching a suffix, transactionally ----
pruneSuffix dir suf =
  hits = ls dir |> List.filter (Str.endsWith suf);
  us = List.map (fn n -> rm "{dir}/{n}") hits;
  print "pruned {List.len hits} '{suf}' file(s) from {dir}".

> scaffold "/tmp/proj".
> lineCountAll "/tmp/proj/src".
> u = writePath "/tmp/proj/tmp1.bak" "junk";
  writePath "/tmp/proj/tmp2.bak" "junk".
> pruneSuffix "/tmp/proj" ".bak".

# summary: scaffold a project dir tree; count lines in a dir; prune files by suffix.
