rm -f /tmp/ck-fail.flag
# NOTE: full sweep takes ~12-15 min (qemu boots + 33 examples + 3-tier dispatch)
#!/bin/sh
# check-all.sh -- the four profiles + the std proof pass, end to end.
set -e
cd "$(dirname "$0")"
ROOT="$(pwd)"
echo "== fprc =="                && (cd fp-risc && make -s fpr) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== stdcheck =="            && (cd fp-risc && ./fpr stdcheck std/checkdemo.fpr | tail -1) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== stdcheck: the REAL std library (lifted lambdas) ==" && (cd fp-risc && ./fpr stdcheck std/std.fpr > /tmp/ck-std.out 2>&1; grep -q "stdcheck: OK" /tmp/ck-std.out && grep -q "pow2 (n : \[0,+inf\])" /tmp/ck-std.out && grep -q "wcet: n·2 ops" /tmp/ck-std.out && grep -qE "retryN.*UNSAFE" /tmp/ck-std.out && echo "std/std.fpr checkable: pow2 static (n·2), retryN carries its ω(step) equation") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== WCET ratchet: preemption-latency ceiling (system.fpr) ==" && (cd fp-risc && tools/wcet-ratchet.sh programs/system.fpr 200 rv64) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== BareMetal =="           && (cd fp-risc && make -s bare-metal-run PROG=tests/stduse.fpr 2>/dev/null | grep "std:") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Wide ABI: arity 24, wide TCO, Tup4..8 ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/wideabi.fpr 2>/dev/null | grep -a "WIDEABI HOLDS") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Floats: F64/F32 in the AOT tier ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/float.fpr 2>/dev/null | grep -a "FLOATS HOLD" && printf 'main =\n  t = (1.5, 2.5);\n  print "{t}".\n' > /tmp/ck-fneg.fpr && LC_ALL=C.UTF-8 ./fprc --profile=bare-metal --prelude=core/prelude.fpr /tmp/ck-fneg.fpr /tmp/ck-fneg.s 2>&1 | grep -q "render is tid-directed" && echo "float-in-structure str/print: compile-time refusal (guard holds)") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Float columns: declared layout + specialized float loops ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/fvec2.fpr 2>/dev/null | grep -a "FLOATVEC2 HOLDS" && grep -q "fadd.d" build/prog.s && grep -q "li t1, 4" build/prog.s && echo "column loops emit float instructions and guard on the FLOAT rep") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Literal suffixes: 2f / 1.5f F32, 1.5 / 1.5d / 1e3 F64 ==" && (cd fp-risc && printf 'main =\n  a = 2f;\n  b = 1.5f;\n  c = 1.5d;\n  d = 1.5;\n  e = 1e3;\n  print "{F32.str (a + b)} {F64.str (c + d)} {F64.str e}".\n' > /tmp/ck-suf.fpr && make -s bare-metal-run PROG=/tmp/ck-suf.fpr 2>/dev/null >/dev/null; cp /tmp/ck-suf.fpr tests/_cksuf.fpr; make -s bare-metal-run PROG=tests/_cksuf.fpr 2>/dev/null | grep -a "3.5 3 1000"; rm -f tests/_cksuf.fpr) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Floats: F64/F32 raw-bits, IEEE, dtoa, refusal guard ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/float.fpr 2>/dev/null | grep -a "FLOATS HOLD" && printf 'main = print (1.5, 2.5).\n' > /tmp/ck-fneg.fpr && LC_ALL=C.UTF-8 ./fprc --profile=bare-metal --prelude=core/prelude.fpr /tmp/ck-fneg.fpr /tmp/ck-fneg.s 2>&1 | grep -q "render is tid-directed" && echo "float-in-structure print: refused with the restriction named") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== QOSPortable app =="     && (cd fp-risc && make -s qos-app PROG=tests/hello.fpr >/dev/null 2>&1) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== QOSPortable host+run ==" && (cd qos && make -s portable 2>/dev/null && ./qosp --yes ../fp-risc/app.qa | grep "=>") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== MVU: the elm surface (App / Ev / subs) on the engine ==" && (cd fp-risc && make -s qos-app PROG=tests/mvutick.fpr >/dev/null 2>&1 && cd ../qos && timeout 60 ./qosp --yes ../fp-risc/app.qa 2>/dev/null | grep -q "final count=31.*4 statics builds" && cd ../fp-risc && make -s qos-app PROG=tests/mvugame.fpr >/dev/null 2>&1 && cd ../qos && timeout 60 ./qosp --yes ../fp-risc/app.qa 2>/dev/null | tr -d '\r' > /tmp/ck-mvug.out; grep -q "gr f2: x=1 vp=32x8" /tmp/ck-mvug.out && grep -aq "game over \[mvu: 3 frames, 1 statics builds\]" /tmp/ck-mvug.out && echo "mvutick: STick-only ticks; mvugame: scripted SKeys -> exact 3-frame run on a custom render service") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== MVU: LV.server -- the LiveView wire over the socket tier ==" && qos/tests-host/mvuweb-check.sh 2>/dev/null | tail -1 || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== MVU: input/display service-roundtrip latency (mvulat, headless) ==" && (cd fp-risc && make -s qos-app PROG=tests/mvulat.fpr >/dev/null 2>&1 && cd ../qos && timeout 60 ./qosp --yes ../fp-risc/app.qa 2>/dev/null | tr -d '\r' > /tmp/ck-mvulat.out; grep -aq "lat input-poll rt: n=1000 min=" /tmp/ck-mvulat.out && grep -aq "lat render rt: n=500 min=" /tmp/ck-mvulat.out && grep -aq "lat key->update: n=400 min=" /tmp/ck-mvulat.out && grep -a "lat key->update" /tmp/ck-mvulat.out | tail -1) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== std.compile: the fpr compiler behind a unix socket (editor loop) ==" && (cd fp-risc && python3 tools/fprd.py /tmp/ck-fprd.sock > /tmp/ck-fprd.log 2>&1 & FPRD=$!; sleep 1; (cd fp-risc && make -s qos-app PROG=tests/editor.fpr >/dev/null 2>&1) && (cd qos && rm -f /tmp/ck-ed.img && FPRD_SOCK=/tmp/ck-fprd.sock FPR_DISK=/tmp/ck-ed.img timeout 120 ./qosp --yes ../fp-risc/app.qa 2>/dev/null | tr -d '\r' | grep -a "editor: compiled .*B of qos-portable asm; stored ed/hello.fpr (14B) + ed/hello.s .*readback ok); bad source -> Err ok"); R=$?; kill $FPRD 2>/dev/null; exit $R) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== dtree: histogram decision tree, F64 columns, == GHC reference ==" && (cd fp-risc && make -s qos-app PROG=tests/dtree.fpr >/dev/null 2>&1 && cd ../qos && timeout 120 ./qosp --yes ../fp-risc/app.qa 2>/dev/null | tr -d '\r' > /tmp/ck-dtree.out; grep -q "nodes=133 depth=8" /tmp/ck-dtree.out && grep -q "test  acc: 0.949" /tmp/ck-dtree.out && grep -q "root split: col 1 @ -0.937404442753177" /tmp/ck-dtree.out && echo "noisy-XOR tree == Haskell reference bit-for-bit (133 nodes, test 0.949, same root split)") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== F64 transcendentals: freestanding log/log2/exp/pow/sin/cos ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/fmath.fpr 2>/dev/null | tr -d '\r' | grep -a "FMATH HOLDS (16 checks)") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Memory: big blocks come back (the bigfree LIFO) ==" && (cd fp-risc && make -s qos-app PROG=tests/bigfree.fpr >/dev/null 2>&1 && cd ../qos && timeout 120 ./qosp --yes ../fp-risc/app.qa 2>/dev/null | grep -a "BIGFREE HOLDS") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== big frames: 300-slot function, 12-bit imm rule retired ==" && (cd fp-risc && make -s qos-app PROG=tests/bigframe.fpr >/dev/null 2>&1 && cd ../qos && ./qosp --yes ../fp-risc/app.qa 2>/dev/null | grep -q "bigframe: sum3=57569 add3=70315" && cd ../fp-risc && make -s bare-metal-run PROG=tests/bigframe.fpr 2>/dev/null | tr -d '\r' | grep -aq "sum3=57569" && echo "2.4KB frame: qx64 + rv64 agree (chunked prologue, deep slots via t2)") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== linear PAPs: partials + lambdas may hold linear values ==" && (cd fp-risc && make -s qos-app PROG=tests/linpap.fpr >/dev/null 2>&1 && cd ../qos && ./qosp --yes ../fp-risc/app.qa 2>/dev/null | grep -q "linpap: x=5 y=10 z=108" && cd ../fp-risc && printf 'f : Vector -> Int -> (Int, Vector) .\nf v i = Vec.get i v.\nu : Vector -> Int .\nu v =\n  h = f v;\n  (a, v2) = h 1;\n  (b, v3) = h 1;\n  _ = Vec.free v2; _ = Vec.free v3;\n  a + b.\nmain = "x".\n' > /tmp/ck-linpap.fpr && LC_ALL=C.UTF-8 ./fprc --profile=qos-portable --prelude=core/prelude.fpr /tmp/ck-linpap.fpr /tmp/ck-linpap.s 2>&1 | grep -q "linear variable 'h' used 2 time(s)" && echo "linear PAP consumed-once holds; double-apply still refused by name") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== linearity: unannotated misuse refused (the closed audit hole) ==" && (cd fp-risc && printf 'main =\n  v = Vec.push 1 (Vec.new Unit);\n  _ = Vec.free v;\n  _ = Vec.free v;\n  "x".\n' > /tmp/ck-lin1.fpr && LC_ALL=C.UTF-8 ./fprc --profile=bare-metal --prelude=core/prelude.fpr /tmp/ck-lin1.fpr /tmp/ck-lin1.s 2>&1 | grep -q "linear variable 'v' used 2 time(s)" && printf 'g v = (Vec.len v, Vec.len v).\nmain = _ = g (Vec.new Unit); "x".\n' > /tmp/ck-lin2.fpr && LC_ALL=C.UTF-8 ./fprc --profile=bare-metal --prelude=core/prelude.fpr /tmp/ck-lin2.fpr /tmp/ck-lin2.s 2>&1 | grep -q "in g: linear variable 'v' used 2 time(s)" && echo "double-free in main and sigless double-use both refused by name") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== ergonomics: arm/lambda bindings + negative literals ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/ergo.fpr 2>/dev/null | tr -d '\r' | grep -a "ergo: pos8 neg-15 zero0 f5=36 neg=15 fneg=5 f32=-3") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== termination measures: declared, verified, unsafe retired ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/measure.fpr 2>/dev/null | tr -d '\r' | grep -a "measure: 10 120 55 (zero unsafe markers)" && printf 'bad : (n : Int | measure n) -> Int .\nbad n = bad n.\nmain = "x".\n' > /tmp/ck-m1.fpr && LC_ALL=C.UTF-8 ./fprc --profile=bare-metal --prelude=core/prelude.fpr /tmp/ck-m1.fpr /tmp/ck-m1.s 2>&1 | grep -q "does not decrease" && printf 'cnt : (n : Int | measure n) -> Int .\ncnt n | n == 0 = 0.\ncnt n = cnt (n - 1).\nmain = "x".\n' > /tmp/ck-m2.fpr && LC_ALL=C.UTF-8 ./fprc --profile=bare-metal --prelude=core/prelude.fpr /tmp/ck-m2.fpr /tmp/ck-m2.s 2>&1 | grep -q "FLOOR (measure >= 0) is not derivable" && echo "three shapes verified; non-decrease and missing floor both refused") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== std.uart: linear phase-typed handle over UART.qa (bare metal, IRQ tx+rx) ==" && (cd fp-risc && make -s bare-metal PROG=tests/uartsvc.fpr >/dev/null 2>&1 && (sleep 3; printf 'ABC'; sleep 8) | timeout 30 qemu-system-riscv64 -accel tcg,thread=multi -machine virt -smp 2 -m 256M -nographic -bios none -kernel image.elf 2>/dev/null | tr -d '\r' > /tmp/ck-uart.out; grep -aq "UARTDMA\[payload-0123456789\]" /tmp/ck-uart.out && grep -a "uartsvc: tx=28B flushed; rx=3B first=65" /tmp/ck-uart.out) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== std.uart on QOS Portable (same protocol, synchronous backend) ==" && (cd fp-risc && make -s qos-app PROG=tests/uartsvc.fpr >/dev/null 2>&1 && (sleep 1; printf 'XY'; sleep 3) | timeout 30 ../qos/qosp --yes app.qa 2>/dev/null | tr -d '\r' | grep -a "uartsvc: tx=28B flushed; rx=2B first=88") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== /services/uart: the Svc-funnel route to UART.qa (capability-gated) ==" && (cd fp-risc && make -s qos-app PROG=tests/uartroute.fpr >/dev/null 2>&1 && (sleep 1; printf 'hi'; sleep 3) | timeout 30 ../qos/qosp --yes app.qa 2>/dev/null | tr -d '\r' | grep -a "uartroute: wrote 15B via /services/uart; rx=\"hi\"") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== std.uart safety: write-before-arm and handle reuse REFUSED ==" && (cd fp-risc && printf 'UM = use "../programs/mods/uart".\nU = use "../std/uart".\nmain =\n  svc = spawn UM.actor;\n  h = U.open svc;\n  (n, u2) = U.write h "too-early";\n  _ = U.close u2;\n  "x".\n' > build/ck-uneg1.fpr && LC_ALL=C.UTF-8 ./fprc --profile=qos-portable --prelude=core/prelude.fpr build/ck-uneg1.fpr /tmp/ck-un1.s 2>&1 | grep -q "cannot unify Uart.* with UartCfg" && printf 'UM = use "../programs/mods/uart".\nU = use "../std/uart".\nmain =\n  svc = spawn UM.actor;\n  h = U.open svc;\n  h2 = U.params h 1;\n  h3 = U.buffer h 4096;\n  u = U.arm h3;\n  _ = U.close u;\n  _ = U.arm h2;\n  "x".\n' > build/ck-uneg2.fpr && LC_ALL=C.UTF-8 ./fprc --profile=qos-portable --prelude=core/prelude.fpr build/ck-uneg2.fpr /tmp/ck-un2.s 2>&1 | grep -q "linear variable .h. used 2 time(s)" && echo "phase misuse = type error; handle aliasing = linearity error") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Timer.qa: aux-hart CLINT bridge (native) + sleeper fallback (qosp) + /services/timer route ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/timer.fpr 2>/dev/null | grep -aq "timer: mode=1 sleep50=ok after=ok order=ok" && make -s qos-app PROG=tests/timer.fpr >/dev/null 2>&1 && cd ../qos && ./qosp --yes ../fp-risc/app.qa 2>/dev/null | grep -q "timer: mode=0 sleep50=ok after=ok order=ok" && cd ../fp-risc && make -s qos-app PROG=tests/timerroute.fpr >/dev/null 2>&1 && cd ../qos && ./qosp --yes ../fp-risc/app.qa 2>/dev/null | grep -q "timerroute: write=ok fire=ok" && echo "hardware deadline on the irq hart; sleeper children on qosp; routed fire through the funnel") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== linearity: wildcard discard of a linear value REFUSED ==" && (cd fp-risc && printf 'main =\n  v = Vec.new Unit;\n  _ = Vec.push 1 v;\n  "x".\n' > /tmp/ck-wild1.fpr && LC_ALL=C.UTF-8 ./fprc --profile=bare-metal --prelude=core/prelude.fpr /tmp/ck-wild1.fpr /tmp/ck-wild1.s 2>&1 | grep -q "a linear value is DISCARDED" && printf 'main =\n  v = Vec.push 1 (Vec.new Unit);\n  (a, _) = Vec.get 0 v;\n  "{a}".\n' > /tmp/ck-wild2.fpr && LC_ALL=C.UTF-8 ./fprc --profile=bare-metal --prelude=core/prelude.fpr /tmp/ck-wild2.fpr /tmp/ck-wild2.s 2>&1 | grep -q "a linear value is DISCARDED" && echo "block-statement and tuple-pattern wildcard leaks both refused") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== std.livereload: hot module swap from the disk store, gate refuses drift ==" && (cd fp-risc && make -s qos-app PROG=tests/livereload.fpr >/dev/null 2>&1 && make -s plugsyms >/dev/null 2>&1 && make -s plugin-qa PROG=tests/mathv1.fpr PLUGSLOT=0 >/dev/null 2>&1 && make -s plugin-qa PROG=tests/mathv2.fpr PLUGSLOT=1 >/dev/null 2>&1 && make -s plugin-qa PROG=tests/mathbad.fpr PLUGSLOT=2 >/dev/null 2>&1 && python3 tools/mkdisk.py /tmp/ck-lr.img 8 mathv1.qa mathv2.qa mathbad.qa >/dev/null && FPR_DISK=/tmp/ck-lr.img timeout 60 ../qos/qosp --yes app.qa 2>/dev/null | tr -d '\r' | grep -a "livereload: v1: 20 22 | v2 (same actor, acc kept): 30 | bad: refused | still v2: 36 | acc=108") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== first-class paths: @Shape literals + schema tier + refusals (docs/PATHS.md) ==" && (cd fp-risc && make -s qos-app PROG=tests/paths.fpr >/dev/null 2>&1 && timeout 60 ../qos/qosp --yes app.qa 2>/dev/null | grep -aq "paths: OK hp=99 name=zed fg=7 comp-fg=8 via-str hp=250 tag=live segs=ui.fg leaves=4 bad=no schema leaf 'ui.nope'" && printf 'M9 = {hp : Int}.\nmain = p = @M9.nmae; p.get {hp = 1}.\n' > /tmp/ck-badpath.fpr && LC_ALL=C.UTF-8 ./fprc --profile=qos-portable --target=qx64 /tmp/ck-badpath.fpr /tmp/ck-badpath.s 2>&1 | grep -q "M9 has no field 'nmae'" && echo "typed literals, compose, string sets/gets by tag, bad path Err'd at runtime + bad field refused at compile") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== pathnotes: value-space iteration on the Notes app (paths + port + livereload) ==" && (cd fp-risc && make -s qos-app PROG=tests/pathnotes.fpr >/dev/null 2>&1 && make -s plugsyms >/dev/null 2>&1 && make -s plugin-qa PROG=tests/notesed1.fpr PLUGSLOT=0 >/dev/null 2>&1 && make -s plugin-qa PROG=tests/notesed2.fpr PLUGSLOT=1 >/dev/null 2>&1 && make -s plugin-qa PROG=tests/notesedbad.fpr PLUGSLOT=2 >/dev/null 2>&1 && python3 tools/mkdisk.py /tmp/ck-pn.img 8 notesed1.qa notesed2.qa notesedbad.qa >/dev/null && FPR_DISK=/tmp/ck-pn.img timeout 60 ../qos/qosp --yes app.qa 2>/dev/null | tr -d '\r' > /tmp/ck-pn.out; grep -aq "pathnotes: OK notes=Third note|Fourth one n=4 cap=2 ui=live ver=caps.v2 log=refused notesedbad" /tmp/ck-pn.out && grep -aq "ui.tag=live" /tmp/ck-pn.out && echo "schema sets + nested leaf + live cap retune; edit-fn hot-swapped v1->caps.v2 mid-run, impostor refused; inspector walked the model") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== sketch tier: FPR programs INTERPRETED (actors + MVU + paths under fpr sol) ==" && (cd fp-risc && LD_LIBRARY_PATH=/usr/lib/llvm-18/lib timeout 90 ./fpr sol tests/paths.fpr 2>/dev/null | grep -aq "paths: OK hp=99 name=zed fg=7 comp-fg=8 via-str hp=250 tag=live segs=ui.fg leaves=4" && LD_LIBRARY_PATH=/usr/lib/llvm-18/lib timeout 120 ./fpr sol tests/mvutick.fpr 2>/dev/null | grep -aq "mvutick: final count=31, arena 0g/0MB \[mvu: 31 frames, 4 statics builds\]" && LD_LIBRARY_PATH=/usr/lib/llvm-18/lib timeout 90 ./fpr sol tests/hello.fpr 2>/dev/null | grep -aq "hello from a .qa: fold(1..10)=55 clamp=55" && echo "paths byte-identical, std.MVU engine (render worker + subs + statics cache) on green actors, std.fpr Struct via language-matched module resolution") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== QAR2 integrity: flipped byte refused before copy ==" && (cd qos && python3 - <<'PY' || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
b = bytearray(open('../fp-risc/app.qa','rb').read()); b[-100] ^= 0xFF
open('/tmp/ck-tamper.qa','wb').write(bytes(b))
PY
./qosp --yes /tmp/ck-tamper.qa 2>&1 | grep -q "sha256 mismatch" && echo "tamper refused: sha256 mismatch (named, pre-copy)")
echo "== Log plane: host lines land in the app's /logs/host ring (ABI v4) ==" && (cd fp-risc && make -s qos-app PROG=tests/hostlog.fpr >/dev/null 2>&1 && cd ../qos && ./qosp --yes ../fp-risc/app.qa 2>/dev/null | grep "HOST RING POPULATED") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Log plane: panic last words persist (sys/panic kv record) ==" && (cd fp-risc && make -s qos-app PROG=tests/panicpersist.fpr >/dev/null 2>&1 && cd ../qos && rm -f qos-store/panicpersist.kv && { ./qosp --yes ../fp-risc/app.qa >/dev/null 2>&1 || true; } && grep -q "sys/panic" qos-store/panicpersist.kv && grep -q "deliberate last words" qos-store/panicpersist.kv && echo "panic record persisted: sys/panic + last words on the kv log") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Log plane: echo rate limit (rings never limited) ==" && (cd fp-risc && make -s qos-app PROG=tests/logstorm.fpr >/dev/null 2>&1 && cd ../qos && ./qosp --yes ../fp-risc/app.qa 2>/dev/null > /tmp/ck-storm.out; E=$(grep -c "^\[log\] line" /tmp/ck-storm.out); grep -q "rings intact" /tmp/ck-storm.out && grep -q "ring seq 100" /tmp/ck-storm.out && [ "$E" -lt 40 ] && echo "storm: $E/100 echoed, suppression named, ring holds all 100") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Grow attribution: the counted gateway names its callers ==" && (cd fp-risc && make -s qos-app PROG=tests/growlog.fpr >/dev/null 2>&1 && cd ../qos && ./qosp --yes ../fp-risc/app.qa 2>/dev/null | grep -E "growlog: [0-9]+ events, newest \[#[0-9]+ (slab|slab-spare|buckets|big-block|stack) a[0-9]+ want") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== QOS-aarch64: x28 hart discipline (no TLS, Darwin-proof) ==" && (if command -v qemu-aarch64 >/dev/null && command -v aarch64-linux-gnu-gcc >/dev/null; then cd fp-risc && make -s qos-app-macos PROG=tests/actors.fpr >/dev/null 2>&1 && aarch64-linux-gnu-objdump -d build/qosapp-a64.elf | grep -cE "str[[:space:]]+x28|ldr[[:space:]]+x28" | grep -qx 0 && cd ../qos && make -s portable-a64 >/dev/null 2>&1 && FPR_HARTS=4 timeout 60 qemu-aarch64 ./qosp-a64 --yes ../fp-risc/app.qa >/dev/null 2>&1 && FPR_HARTS=1 qemu-aarch64 ./qosp-a64 --yes ../fp-risc/app.qa 2>/dev/null > /tmp/ck-a64.out && (cd ../fp-risc && make -s qos-app PROG=tests/actors.fpr >/dev/null 2>&1) && FPR_HARTS=1 ./qosp --yes ../fp-risc/app.qa 2>/dev/null > /tmp/ck-x64.out && cmp -s /tmp/ck-a64.out /tmp/ck-x64.out && echo "x28 world: zero spills in image, 4-hart run green, FPR_HARTS=1 qa64==qx64 byte-identical"; else echo "skipped (needs qemu-aarch64 + aarch64-linux-gnu-gcc)"; fi) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Desktop GL: GLFW window + synthetic-evdev keys (Xvfb) ==" && (if command -v xvfb-run >/dev/null && command -v xdotool >/dev/null && ldconfig -p 2>/dev/null | grep -q libglfw; then fp-risc/tools/gfx-gl-check.sh; else echo "skipped (needs xvfb-run + xdotool + libglfw)"; fi) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== QOSNative kernel =="    && (cd qos && make -s native disk.img >/dev/null && (printf 'yyyy'; sleep 8) | timeout 14 qemu-system-riscv64 -accel tcg,thread=multi -machine virt -smp 2 -m 256M -nographic -bios none -kernel qos-native.elf -drive file=disk.img,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 2>/dev/null | grep -a "app launcher" | head -1) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== QAR2 process load: build, seed, launch, exit ==" && (cd fp-risc && printf 'main = "qar2 process ran".\n' > /tmp/ck-proc.fpr && printf 'name = "CkProc"\nid = "CkProc"\nentry = "n/a"\nloadMode = "process"\nversion = "1"\n' > /tmp/CkProc.toml && tools/build-process-app.sh /tmp/ck-proc.fpr /tmp/CkProc.toml /tmp/ck-proc.qa >/dev/null 2>&1 && cd ../qos && python3 ../fp-risc/tools/mkdisk.py /tmp/ck-disk.img 8 /tmp/ck-proc.qa >/dev/null && (printf 'yyyy'; sleep 6; printf '1'; sleep 3; sleep 9) | timeout 24 qemu-system-riscv64 -accel tcg,thread=multi -machine virt -smp 2 -m 256M -nographic -bios none -kernel qos-native.elf -drive file=/tmp/ck-disk.img,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 2>/dev/null | tr -d '\r' | grep -a "process exited: qar2 process ran") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Transparent ACBs: process spawn/steal across harts, pid-tagged ==" && (cd fp-risc && printf 'name = "CkPar"\nid = "CkPar"\nentry = "n/a"\nloadMode = "process"\nversion = "1"\n' > /tmp/CkPar.toml && tools/build-process-app.sh tests/tpar.fpr /tmp/CkPar.toml /tmp/ck-par.qa >/dev/null 2>&1 && cd ../qos && python3 ../fp-risc/tools/mkdisk.py /tmp/ck-par.img 8 /tmp/ck-par.qa >/dev/null && (printf 'yyyy'; sleep 6; printf '1'; sleep 16) | timeout 30 qemu-system-riscv64 -accel tcg,thread=multi -machine virt -smp 2 -m 256M -nographic -bios none -kernel qos-native.elf -drive file=/tmp/ck-par.img,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 2>/dev/null | tr -d '\r' | grep -a "process exited: tpar: ok" | grep -a "harts=2") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Numeric: ONE surface number, VNum/JD underneath, 3 tiers agree ==" && (cd fp-risc && export LD_LIBRARY_PATH=/usr/lib/llvm-18/lib; printf 'mix acc x = acc * 0.999 + x * 1.5 + 0.25.\nfill : unsafe Vector -> Int -> Int -> Vector .\nfill v i lim | i > lim = v.\nfill v i lim = fill (Vec.push i v) (i + 1) lim.\n> xs = fill (Vec.new Unit) 1 200000;\n  (s, xs2) = Vec.fold mix 0.0 xs;\n  u = print "num3: {1.5 + 1} {s}";\n  Vec.free xs2 .\n' > /tmp/ck-num.sol; A=$(timeout 180 ./fpr sol /tmp/ck-num.sol 2>/dev/null | grep -a num3); B=$(SOL_JIT=hand timeout 180 ./fpr sol /tmp/ck-num.sol 2>/dev/null | grep -a num3); C=$(SOL_JIT=0 timeout 300 ./fpr sol /tmp/ck-num.sol 2>/dev/null | grep -a num3); [ -n "$A" ] && [ "$A" = "$B" ] && [ "$B" = "$C" ] && echo "float literal is a Numeric; llvm==hand==interp: $A") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== ONE grammar, two profiles (both.sol) ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/both.sol 2>/dev/null | grep -a "both:" && cd tests && LD_LIBRARY_PATH=/usr/lib/llvm-18/lib ../fpr sol both.sol | grep "both:") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Memory: linear frames (Arc-flat) ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/frames.fpr 2>/dev/null | grep -a "ARC FLAT") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Memory: autodrop (the drop law, compiler-discharged) ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/autodrop.fpr 2>/dev/null | grep -a "AUTODROP HOLDS: 600 undropped-by-hand round trips") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Memory: ARC.qa audit ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/arcaudit.fpr 2>/dev/null | grep -a "ARC.qa: clean") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== fpr commit / store resolution ==" && (T=$(mktemp -d); cd $T; printf 'greet n = n + 100.\ntwice x = x * 2.\n' > m.fpr; FPR="$ROOT/fp-risc/fpr"; $FPR commit m.fpr >/dev/null; H=$(awk '{print $3}' .fpr/versions.db); printf 'M = use "m#%s".\nmain = print "{M.twice 21}".\n' $H > c.fpr; rm m.fpr; LC_ALL=C.UTF-8 $FPR --target=rv64 --prelude="$ROOT/fp-risc/core/prelude.fpr" c.fpr /tmp/c.s 2>&1 | grep "resolved from .fpr store"; cd /; rm -rf $T) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== THE FOLD, COMPLETE: one parser, VM as a target ==" && (cd fp-risc/sol/examples && export LD_LIBRARY_PATH=/usr/lib/llvm-18/lib; echo 0 > /tmp/sol-counter.txt; ok=0; total=0; for f in *.sol; do total=$((total+1)); timeout 12 ../../fpr sol "$f" >/tmp/ck.$f 2>&1 || true; bad=0; grep -qE "PANIC|unexpected|parse error|SAFETY" /tmp/ck.$f && bad=1; case "$f" in bad_double.sol|bad_leak.sol) bad=0;; esac; [ $bad -eq 0 ] && ok=$((ok+1)); done; echo "examples green under the ONE parser: $ok/$total (~2min leg)"; cd ../../ && ./fpr --target=bytecode tests/both.sol 2>/dev/null | head -1 | grep -q "arity" && echo "bytecode target emits (fpr --target=bytecode)") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Vec dispatch lattice: GPU/JIT/interp agree ==" && (cd fp-risc/sol/examples && export LD_LIBRARY_PATH=/usr/lib/llvm-18/lib; A=$(SOL_GPU_MIN=1000 timeout 180 ../../fpr sol dispatch.sol 2>/dev/null | grep -a checksum); B=$(SOL_GPU=0 timeout 180 ../../fpr sol dispatch.sol 2>/dev/null | grep -a checksum); [ -n "$A" ] && [ "$A" = "$B" ] && echo "GPU==JIT checksum: $A" || echo "TIER MISMATCH: gpu[$A] jit[$B]") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Sol ML pipeline: range fill, GPU uniform captures, record-SoA JIT folds, 3 tiers identical ==" && (cd fp-risc/sol/examples && export LD_LIBRARY_PATH=/usr/lib/llvm-18/lib; O=$(SOL_JIT_DEBUG=1 SOL_GPU_MIN=1000 timeout 300 ../../fpr sol mlpipe.sol 2>&1); echo "$O" | grep -q "ok a " && echo "$O" | grep -q "uniform capture(s)" && echo "$O" | grep -q "compiled vecfold<gA> over SoA layout r" && echo "$O" | grep -q "compiled vecmapr<mkPt>" && A=$(echo "$O" | grep -a "pred-checksum") && B=$(SOL_GPU=0 timeout 300 ../../fpr sol mlpipe.sol 2>/dev/null | grep -a "pred-checksum") && C=$(SOL_JIT=0 timeout 900 ../../fpr sol mlpipe.sol 2>/dev/null | grep -a "pred-checksum") && [ -n "$A" ] && [ "$A" = "$B" ] && [ "$B" = "$C" ] && echo "quadratic fit converged; GPU uniforms + record duals; gpu==jit==interp: $A") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Sol NN: feed-forward + backprop over Matrix-on-Vec ==" && (cd fp-risc/sol/examples && export LD_LIBRARY_PATH=/usr/lib/llvm-18/lib; O=$(SOL_JIT_DEBUG=1 timeout 180 ../../fpr sol nn.sol 2>&1); echo "$O" | grep -aq "nn: OK" && echo "$O" | grep -q "compiled vecmap<relu>" && echo "$O" | grep -aq "ok mse<0.02" && echo "MLP learned x1*x2 (22x under linear-best); relu batch on the Vec JIT; nested-Vec probe ok") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Sol plot: SVG/SMIL backend (charts + animations as text) ==" && (cd fp-risc/sol/examples && export LD_LIBRARY_PATH=/usr/lib/llvm-18/lib; rm -f plot-*.svg; timeout 120 ../../fpr sol plotdemo.sol 2>/dev/null | grep -aq "plotdemo: wrote 5 svg" && python3 -c "import xml.etree.ElementTree as ET,glob;fs=sorted(glob.glob('plot-*.svg'));assert len(fs)==5,fs;an=sum(len(ET.parse(f).getroot().findall('.//{http://www.w3.org/2000/svg}animate')) for f in fs);assert an==5,an" && echo "5 charts well-formed; 5 SMIL animate elements across wave+orbit") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== auto-tabling: gated, correct, braked ==" && (cd fp-risc/sol/examples && export LD_LIBRARY_PATH=/usr/lib/llvm-18/lib; SOL_GPU=0 SOL_TABLE_STATS=1 timeout 60 ../../fpr sol tabling.sol 2>&1 | grep -aE "dropped|tabling:|\[table\] fib" | head -3) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Mat4*Vec4: operator -> axpb column loops, EXECUTED ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/matvec.fpr 2>/dev/null | tr -d '\r' > /tmp/ck-mv.out; grep -a "MATVEC AGREES" /tmp/ck-mv.out && grep -a "spec loop EXECUTED" /tmp/ck-mv.out && grep -q "matvec-specialized" build/prog.s && echo "record SoA columns + in-place spec loop: emitted AND run") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Vec.filter: eager COMPACTION in place (the decision, tested) ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/vfilter.fpr 2>/dev/null | tr -d '\r' | grep -a "FILTER COMPACTS") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Vec fusion: adjacent maps -> ONE column loop ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/fuse.fpr 2>/dev/null | tr -d '\r' | grep -a "FUSION HOLDS" && grep -q "_x5fvfuse_x5f" build/prog.s && echo "composites specialized in asm") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Vec fixpoint + write-back fold: 3-chain collapses, fold-of-map fuses ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/vecfuse2.fpr 2>/dev/null | tr -d '\r' | grep -a "vecfuse2: OK" && grep -q "_x5fvfuse_x5f1_x5f" build/prog.s && grep -q "fpr_vspec_wfold" build/prog.s && echo "round-2 composite and the wfold loop both in the asm") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Vec record folds: named fns dualize; declines stay NAMED; x64 says the tier is off ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/recfold.fpr 2>/dev/null | tr -d '\r' | grep -a "recfold: OK 1015050 5050 15150" && LC_ALL=C.UTF-8 ./fprc --profile=bare-metal --prelude=core/prelude.fpr tests/recfold.fpr /tmp/ck-rf.s 2>&1 | grep -qa "vec note: Vec.fold over \`raStep\`" && grep -q "SoA dualized" /tmp/ck-rf.s && LC_ALL=C.UTF-8 ./fprc --profile=qos-portable --prelude=core/prelude.fpr tests/recfold.fpr /tmp/ck-rfx.s 2>&1 | grep -qa "specialization tier is OFF on this target" && echo "sxy dualized+executed; record-acc decline named; x64 fallback loud") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== RVV: --rvv links (COMDAT enable shim) and runs under -cpu v=true ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/vecfuse2.fpr RVV=1 2>/dev/null | tr -d '\r' | grep -a "vecfuse2: OK" && grep -q "fpr_rvv_enable,comdat" build/prog.s && grep -q "vsetvli" build/prog.s && echo "vector loops emitted, link-once shim, vector cpu executes them") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Vec edges: SoA<->AoS, lenses, chains, wide records, empty, SIMD prims ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/vecedge.fpr 2>/dev/null | tr -d '\r' > /tmp/ck-vecedge.out; grep -aq "VEC EDGES DONE" /tmp/ck-vecedge.out && ! grep -aq "FAIL" /tmp/ck-vecedge.out && echo "18 interaction probes hold ($(grep -ac "^ok " /tmp/ck-vecedge.out) ok)") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== operator sugar: + / - on Str and List (prelude-backed) ==" && (cd fp-risc && make -s bare-metal-run PROG=tests/opsugar.fpr 2>/dev/null | grep -ac "OPS AGREE" | grep -q 3 && echo "OPS AGREE x3: concat laws hold ((a+b)-b == a; non-suffix - is identity)") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== Ma on gen_view: components over Elem, delta vs reshape ==" && (cd fp-risc && make -s bare-metal-run PROG=programs/maapp.fpr 2>/dev/null | tr -d '\r' > /tmp/ma.out; grep -q "MABEGIN" /tmp/ma.out && grep -a "^ma:" /tmp/ma.out) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== typed holes: ?name refuses w/ type, ?? runs-then-traps ==" && (cd fp-risc && export LD_LIBRARY_PATH=/usr/lib/llvm-18/lib; A=$(./fprc --prelude=core/prelude.fpr tests/holes_named.fpr /tmp/hn.s 2>&1 | grep -ac "typed hole, ?res : Int"); B=$(timeout 30 ./fpr sol tests/holes.sol 2>&1 | grep -ac "prefix ran, sum = 32"); C=$(timeout 30 ./fpr sol tests/holes.sol 2>&1 | grep -ac "SOL PANIC: typed hole"); [ "$A$B$C" = "111" ] && echo "holes: named=compile-refusal-with-type, ??=pipeline-runs-then-traps" || echo "HOLES BROKEN: $A$B$C") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== txn: the SCRIPT is the transaction (abort is total) ==" && (cd fp-risc && export LD_LIBRARY_PATH=/usr/lib/llvm-18/lib; rm -f /tmp/sol-txnabort.txt; timeout 20 ./fpr sol tests/txnabort.sol >/dev/null 2>&1 || true; if [ -e /tmp/sol-txnabort.txt ]; then echo "TXN LEAK: partial state survived a panic"; else echo "abort total: phase-1 write unwritten by phase-2 panic"; fi) || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== handJIT: hand-rolled tier == llvm tier ==" && (cd fp-risc/sol/examples && export LD_LIBRARY_PATH=/usr/lib/llvm-18/lib; A=$(SOL_JIT=hand SOL_GPU=0 timeout 120 ../../fpr sol dispatch.sol 2>/dev/null | grep -a checksum); B=$(SOL_GPU=0 timeout 120 ../../fpr sol dispatch.sol 2>/dev/null | grep -a checksum); C=$(SOL_JIT=hand SOL_GPU=0 timeout 120 ../../fpr sol handint.sol 2>/dev/null | grep -a checksum); D=$(SOL_JIT=0 timeout 300 ../../fpr sol handint.sol 2>/dev/null | grep -a checksum); { [ -n "$A" ] && [ "$A" = "$B" ] && [ -n "$C" ] && [ "$C" = "$D" ]; } && echo "hand==llvm (f64) and hand==interp (i64): $A / $C" || echo "HAND MISMATCH: [$A|$B] [$C|$D]") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
echo "== HostedBytecode (sol) ==" && (cd fp-risc/sol/examples && LD_LIBRARY_PATH=/usr/lib/llvm-18/lib ../../fpr sol stddemo.sol | grep "std via sol") || { echo "** LEG FAILED"; touch /tmp/ck-fail.flag; }
if [ -e /tmp/ck-fail.flag ]; then echo "SWEEP HAS FAILURES (see ** LEG FAILED above)"; exit 1; else echo "ALL LEGS GREEN"; fi
