#!/usr/bin/env python3
"""mkfont.py -- bake a TrueType face into the walker's text atlas.

The GL walker (hal/unix/gfx.c) draws proportional, anti-aliased text
from ONE signed-distance-field atlas compiled into the host: every
glyph 32..126 lives in a 32x32 texel cell with its pen origin at a
fixed spot, so a glyph quad is always "the whole cell, placed at the
pen" and the only per-glyph datum the renderer needs is the advance.
A distance field (not a bitmap) is what keeps the edge crisp at any
size the scene scales it to: the fragment shader thresholds the
sampled distance, so a 20 px em source reads cleanly at 12 px and at
48 px alike.

Outputs (both checked in, regenerate when the face changes):
  hal/unix/font_sdf.h            the atlas bytes + advances, for the host
  fp-risc/programs/mods/fontm.fpr  the advances in milli-em, for layout

    python3 tools/mkfont.py [/path/to/face.ttf]

Needs Pillow, numpy and scipy (pip3 install pillow numpy scipy).
"""
import sys, os
from PIL import Image, ImageDraw, ImageFont
import numpy as np
from scipy.ndimage import distance_transform_edt

FACE = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
EM = 20          # atlas em size in texels
CELL = 32        # texels per glyph cell (square)
COLS = 12        # cells per atlas row (95 glyphs -> 8 rows)
PEN_X, PEN_Y = 5, 23   # pen origin inside a cell (left, baseline; y down)
SPREAD = 5.0     # distance field range in texels (+-)
OVER = 4         # render oversampling

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(os.path.dirname(here))

font = ImageFont.truetype(FACE, EM * OVER)
metrics = ImageFont.truetype(FACE, EM)
ascent, descent = metrics.getmetrics()

rows = (95 + COLS - 1) // COLS
AW, AH = COLS * CELL, rows * CELL
atlas = np.zeros((AH, AW), dtype=np.uint8)
adv = []

for i in range(95):
    ch = chr(32 + i)
    hi = Image.new("L", (CELL * OVER, CELL * OVER), 0)
    d = ImageDraw.Draw(hi)
    d.text((PEN_X * OVER, PEN_Y * OVER), ch, font=font, fill=255, anchor="ls")
    mask = np.asarray(hi) >= 128
    # signed distance in hi-res px: positive outside the ink
    dout = distance_transform_edt(~mask)
    din = distance_transform_edt(mask)
    sd = (dout - din) / OVER           # texel units
    # average down to atlas texels
    sd = sd.reshape(CELL, OVER, CELL, OVER).mean(axis=(1, 3))
    v = 0.5 - sd / (2 * SPREAD)        # 1 deep inside, 0 far outside, 0.5 at the edge
    v = np.clip(v, 0, 1)
    cy, cx = divmod(i, COLS)
    atlas[cy * CELL:(cy + 1) * CELL, cx * CELL:(cx + 1) * CELL] = np.round(v * 255).astype(np.uint8)
    adv.append(metrics.getlength(ch) / EM)

hdr = os.path.join(root, "hal", "unix", "font_sdf.h")
with open(hdr, "w") as f:
    f.write("/* generated by fp-risc/tools/mkfont.py from %s -- do not edit */\n" % os.path.basename(FACE))
    f.write("#define FONT_ATLAS_W %d\n#define FONT_ATLAS_H %d\n#define FONT_CELL %d\n#define FONT_COLS %d\n"
            % (AW, AH, CELL, COLS))
    f.write("#define FONT_EM %d\n#define FONT_PEN_X %d\n#define FONT_PEN_Y %d\n#define FONT_SPREAD %.1ff\n"
            % (EM, PEN_X, PEN_Y, SPREAD))
    f.write("#define FONT_ASCENT %gf\n#define FONT_DESCENT %gf\n" % (ascent / EM, descent / EM))
    f.write("static const float font_adv[95] = {\n")
    for i in range(0, 95, 8):
        f.write("  " + ", ".join("%.5ff" % a for a in adv[i:i + 8]) + ",\n")
    f.write("};\n")
    f.write("static const unsigned char font_atlas[%d] = {\n" % (AW * AH))
    flat = atlas.reshape(-1)
    for i in range(0, len(flat), 32):
        f.write(",".join(str(int(b)) for b in flat[i:i + 32]) + ",\n")
    f.write("};\n")

mod = os.path.join(root, "fp-risc", "programs", "mods", "fontm.fpr")
with open(mod, "w") as f:
    f.write("# fontm.fpr -- metrics of the walker's text face (%s), generated by\n" % os.path.basename(FACE))
    f.write("# tools/mkfont.py.  Advances in milli-em; a line is ascent + descent.\n")
    f.write("# Layout code (scene2d) sums these so it can size and center text\n")
    f.write("# without ever seeing a glyph; the host draws from the same table.\n\n")
    f.write("ascent = %d.\ndescent = %d.\nline = %d.\n\n" % (round(ascent / EM * 1000), round(descent / EM * 1000),
                                                              round((ascent + descent) / EM * 1000)))
    for i, a in enumerate(adv):
        f.write("adv %d = %d.%s\n" % (32 + i, round(a * 1000), "" if 32 + i in (32, 92) else "   # %s" % chr(32 + i)))
    f.write("adv c = %d.\n\n" % round(adv[ord('?') - 32] * 1000))
    f.write("# width of a string in milli-em\n")
    f.write("width s = wGo s 1 (strlen s) 0.\n")
    f.write("wGo s i n acc | i > n = acc.\n")
    f.write("wGo s i n acc = wGo s (i + 1) n (acc + adv (charAt s i)).\n")

# a preview for the eye
Image.fromarray(atlas).save(os.path.join(os.environ.get("FPR_FONT_PREVIEW", "/tmp"), "font_sdf.png"))
print("atlas %dx%d, %d glyphs, ascent %.3f descent %.3f -> %s, %s" % (AW, AH, 95, ascent / EM, descent / EM, hdr, mod))
