#!/usr/bin/env python3
"""mkmesh.py -- STL -> an FP-RISC mesh module for the scene walker.

    mkmesh.py out.fpr name=part.stl [name2=part2.stl ...] [--scale S] [--floor]

Reads binary or ASCII STL, maps OpenSCAD's Z-up frame to the walker's
Y-up one ((x, y, z) -> (x, z, -y): +Y forward becomes -Z, the direction
a player's unit faces), scales (1 model unit = 1000 milli) and emits

    name = "x y z x y z x y z ..." + "..."      # one triangle = 9 ints
    meshes = (name, name) :: ... :: Nil        # for GL.serve

Normals are not exported: the host computes a flat normal per triangle
when it registers the mesh (glMesh), so a low-poly model shades as
facets, which is the look.  Vertex sharing is not attempted either --
flat shading wants every triangle to own its corners.

--floor moves each part so its lowest point sits on y = 0; --scale is
applied before that.  The output is a normal module: `T = use
"models/tank"` then `GL.serve 960 600 "tag" T.meshes`.
"""
import struct, sys


def read_stl(path):
    b = open(path, "rb").read()
    tris = []
    if len(b) >= 84 and not b[:5].lower().startswith(b"solid") or (len(b) >= 84 and 84 + 50 * struct.unpack_from("<I", b, 80)[0] == len(b)):
        n = struct.unpack_from("<I", b, 80)[0]
        for i in range(n):
            o = 84 + 50 * i
            f = struct.unpack_from("<12f", b, o)
            tris.append([(f[3], f[4], f[5]), (f[6], f[7], f[8]), (f[9], f[10], f[11])])
        return tris
    cur = []
    for line in b.decode(errors="replace").splitlines():
        w = line.split()
        if len(w) == 4 and w[0] == "vertex":
            cur.append((float(w[1]), float(w[2]), float(w[3])))
            if len(cur) == 3:
                tris.append(cur)
                cur = []
    return tris


def convert(tris, scale, floor):
    out = []
    for t in tris:
        out.append([(x * scale, z * scale, -y * scale) for (x, y, z) in t])
    if floor and out:
        lo = min(v[1] for t in out for v in t)
        out = [[(x, y - lo, z) for (x, y, z) in t] for t in out]
    return out


def main():
    args = sys.argv[1:]
    scale, floor = 1.0, False
    parts = []
    out = None
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--scale":
            scale = float(args[i + 1]); i += 2; continue
        if a == "--floor":
            floor = True; i += 1; continue
        if out is None:
            out = a
        else:
            name, path = a.split("=", 1)
            parts.append((name, path))
        i += 1
    if out is None or not parts:
        sys.exit(__doc__)
    lines = ["# generated by tools/mkmesh.py -- do not edit; triangles as milli ints (x y z) x 3",
             "unsafe module.", ""]
    names = []
    for name, path in parts:
        tris = convert(read_stl(path), scale, floor)
        chunks = []
        for k in range(0, len(tris), 16):
            words = []
            for t in tris[k:k + 16]:
                for (x, y, z) in t:
                    words += [str(int(round(x * 1000))), str(int(round(y * 1000))), str(int(round(z * 1000)))]
            chunks.append('"' + " ".join(words) + ' "')   # the trailing space keeps chunks apart under +
        lines.append(f"# {name}: {len(tris)} triangles from {path}")
        lines.append(f"{name} = " + "\n  + ".join(chunks) + ".")
        names.append(name)
        print(f"{name}: {len(tris)} triangles")
    lines.append("")
    lines.append("meshes = " + " :: ".join(f'("{n}", {n})' for n in names) + " :: Nil.")
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
