name = "Notes"
id = "TUINotes"
entry = "n/a"
loadMode = "process"
version = "2"

[permissions.required]
"/services/display" = "write"
"/services/keyboard" = "read"

[permissions.optional]
"/services/storage" = "write"
