# docsgen.sol -- embed the static assets (web/shell.html + docs/*.md)
# into programs/mods/docsdata.fpr as string-literal clauses.
#
#   sol tools/docsgen.sol
#
# This IS the static half of the split, made literal: the shell and the
# doc corpus become rodata in the server binary, so the whole docsite is
# one static executable with zero runtime file dependencies. Escaping
# (\\ " {  -- fpr strings interpolate on bare braces) is byte-shovelling,
# so it goes through sed per the division-of-labour rule; the DECISIONS
# (which docs, titles, module shape) live here in Sol. The module is
# written transactionally: complete or absent.

nl = Str.fromCode 10.

# (file, tab title) -- the curated corpus, in tab order
docTable u =
  [("API.md", "API"),
   ("SDK.md", "SDK"),
   ("FUEL-RC-ABI.md", "Fuel + RC ABI"),
   ("SCHED-MODEL.md", "Scheduler"),
   ("STORAGE.md", "Storage"),
   ("QOS-PORTABLE.md", "QOS Portable"),
   ("SYSTEM-QA.md", "System.qa")].

outMod = "programs/mods/docsdata.fpr".

# escape one file into an fpr string-literal body: backslash first,
# then quote, then open-brace (interpolation opener; bare } is fine)
escFile p =
  (rc, out) = sh "sed -e 's/\\\\/\\\\\\\\/g' -e 's/\"/\\\\\"/g' -e 's/\{/\\\\\{/g' docs/{p}";
  chkRc rc p out.
escShell u =
  (rc, out) = sh "sed -e 's/\\\\/\\\\\\\\/g' -e 's/\"/\\\\\"/g' -e 's/\{/\\\\\{/g' web/shell.html";
  chkRc rc "web/shell.html" out.
chkRc 0 p out = out.
chkRc rc p out = error "docsgen: cannot read {p}".

bodyClause (name, title) =
  "body \"{name}\" = \"{escFile name}\".{nl}".
bodyClauses lst = case lst of [] -> "" | e :: r -> "{bodyClause e}{bodyClauses r}".

listRow (name, title) = "(\"{name}\", \"{title}\")".
listRows lst = case lst of
  [] -> ""
| e :: r -> (case r of [] -> listRow e | _ -> "{listRow e},{nl}   {listRows r}").

> tbl = docTable Unit;
  m = "# docsdata.fpr -- GENERATED by tools/docsgen.sol; do not edit.{nl}# The static half of the docsite split: shell + corpus as rodata.{nl}{nl}docs u ={nl}  [{listRows tbl}].{nl}{nl}{bodyClauses tbl}body n = \"\".{nl}{nl}shell u = \"{escShell Unit}\".{nl}";
  u = writePath outMod m;
  print "wrote {outMod}".
