"""genapps.py -- generate runtime/apps_data.c from a set of .qa files.

    tools/genapps.py --entries sym1 sym2 ... -- app1.qa app2.qa ...

Emits two rodata tables consumed by runtime/apps.c:
  fpr_qa_blobs[]    the .qa archives as byte arrays, keyed by their Id
                    (taken from the manifest `id = "..."` line)
  fpr_app_entries[] { "<symbol>", &<symbol> } for each co-compiled entry;
                    the extern PAP objects are defined by the app's own
                    FPRISC code (fprc emits fpr_g_<mangled> for a global).

The entry symbol in the manifest is e.g. "launcher_main"; the FPRISC
global that implements it is `launcher_main`, which fprc emits as the
PAP object `fpr_g_launcher_main`. genapps wires the two together.
"""
import sys, re, os, argparse

def manifest_id(qa_bytes):
    # locate the MANIFEST section from the QAR1 table, read its `id`
    assert qa_bytes[:5] == b"QAR1\n", "not a QAR1 archive"
    body = qa_bytes[5:]
    tbl_end = body.index(b"\n\n")
    table = body[:tbl_end].decode().splitlines()
    payloads = body[tbl_end + 2:]
    for line in table:
        name, off, length = line.split()
        if name == "MANIFEST":
            man = payloads[int(off):int(off) + int(length)].decode()
            m = re.search(r'^\s*id\s*=\s*"([^"]+)"', man, re.M)
            return m.group(1)
    raise SystemExit("no MANIFEST section")

def c_bytes(blob):
    return ",".join(str(b) for b in blob)

def mangle(sym):
    # fprc mangles identifier bytes to fpr_obj_<...>; '_' -> 'x5f', '.' -> 'x2e'
    out = []
    for ch in sym:
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_x%02x" % ord(ch))   # matches fprc: '_'->'_x5f'
    return "".join(out)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--entries", nargs="*", default=[])  # accepted, ignored (name-dispatch is dead)
    ap.add_argument("--out", default="runtime/apps_data.c")
    ap.add_argument("qa", nargs="+")
    a = ap.parse_args()

    out = ["/* GENERATED by tools/genapps.py -- do not edit */",
           "#include \"fpr.h\"",
           "typedef struct { const char *id; const unsigned char *bytes; unsigned long len; } qa_blob_t;",
           "typedef struct { const char *symbol; const pap0_t *pap; } app_entry_t;",
           ""]
    ids = []
    for i, path in enumerate(a.qa):
        blob = open(path, "rb").read()
        appid = manifest_id(blob)
        ids.append(appid)
        out.append(f"static const unsigned char qa_{i}[] = {{{c_bytes(blob)}}};")
    out.append("")
    out.append("const qa_blob_t fpr_qa_blobs[] = {")
    for i, appid in enumerate(ids):
        out.append(f'  {{ "{appid}", qa_{i}, sizeof(qa_{i}) }},')
    out.append("  { 0, 0, 0 }")
    out.append("};")
    out.append("")
    for sym in a.entries:
        out.append(f"extern const pap0_t fpr_obj_{mangle(sym)};")
    out.append("const app_entry_t fpr_app_entries[] = {")
    for sym in a.entries:
        out.append(f'  {{ "{sym}", &fpr_obj_{mangle(sym)} }},')
    out.append("  { 0, 0 }")
    out.append("};")
    open(a.out, "w").write("\n".join(out) + "\n")
    print(f"wrote {a.out}: {len(ids)} apps [{', '.join(ids)}], "
          f"{len(a.entries)} entries")

if __name__ == "__main__":
    main()
