# livegen.sol -- embed web/live.js into programs/mods/livejs.fpr.
#
#   sol tools/livegen.sol
#
# The delta client is ~120 lines of JS and it is STATIC: it never
# changes per app, so it belongs in rodata beside the shell, not on a
# filesystem the server has to trust at runtime. Escaping is
# byte-shovelling (sed); the decision -- one module, one `src` clause --
# lives here.

nl = Str.fromCode 10.

> (rc, js) = sh "sed -e 's/\\\\/\\\\\\\\/g' -e 's/\"/\\\\\"/g' -e 's/\{/\\\\\{/g' web/live.js";
  u = chk rc;
  m = "# livejs.fpr -- GENERATED by tools/livegen.sol; do not edit.{nl}{nl}src u = \"{js}\".{nl}";
  u2 = writePath "programs/mods/livejs.fpr" m;
  print "wrote programs/mods/livejs.fpr".

chk 0 = 0.
chk rc = error "livegen: cannot read web/live.js".
